apiVersion: v1
kind: Service
metadata:
  name: pipeline-app
  labels:
    app: pipeline-app
spec:
  type: ClusterIP
  selector:
    app: pipeline-app
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
