# PostgreSQL Client Authentication Configuration File (Primary)
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local connections
local   all             all                                     trust

# IPv4 local connections
host    all             all             127.0.0.1/32            trust

# Docker network connections
host    all             all             0.0.0.0/0               md5

# Replication connections
host    replication     replicator      0.0.0.0/0               md5
