#!/usr/bin/env bash
# =============================================================================
# 06-join-worker.sh - Join a worker node to the cluster
# =============================================================================
# Run on: WORKER node only
# Run as: root (sudo -E ./06-join-worker.sh)
#
# Prerequisites:
#   - Scripts 01-03 have been run on this worker node
#   - The file configs/worker-join-command.sh has been copied from the
#     control plane (generated by 04-init-control-plane.sh)
#
# Alternatively, set JOIN_COMMAND env var with the full kubeadm join command.
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/00-env.sh"

require_root

log_step "Step 6: Join Worker Node to Cluster"

# ---- Get join command --------------------------------------------------------
JOIN_COMMAND="${JOIN_COMMAND:-}"

if [[ -z "$JOIN_COMMAND" ]]; then
    JOIN_FILE="${CONFIGS_DIR}/worker-join-command.sh"
    if [[ -f "$JOIN_FILE" ]]; then
        JOIN_COMMAND=$(cat "$JOIN_FILE")
        log_info "Join command loaded from $JOIN_FILE"
    else
        log_error "No join command found."
        echo "  Either:"
        echo "    1. Copy configs/worker-join-command.sh from the control plane"
        echo "    2. Export JOIN_COMMAND with the full 'kubeadm join ...' command"
        echo ""
        echo "  To regenerate on the control plane:"
        echo "    kubeadm token create --print-join-command"
        exit 1
    fi
fi

# ---- Check if already joined ------------------------------------------------
if [[ -f /etc/kubernetes/kubelet.conf ]]; then
    log_warn "This node appears to already be part of a cluster."
    log_warn "If you want to rejoin, run: kubeadm reset -f"
    read -rp "Continue anyway? (y/N): " confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        exit 0
    fi
fi

# ---- Configure kubelet node-ip -----------------------------------------------
if [[ -n "$WORKER_IP" ]]; then
    log_info "Setting kubelet node-ip to $WORKER_IP..."
    mkdir -p /etc/default
    cat > /etc/default/kubelet <<EOF
KUBELET_EXTRA_ARGS="--node-ip=${WORKER_IP}"
EOF
fi

# ---- Run join ----------------------------------------------------------------
log_info "Joining cluster..."
log_info "Command: $JOIN_COMMAND"

eval "$JOIN_COMMAND" || {
    log_error "kubeadm join failed. Check the output above."
    echo "  Common issues:"
    echo "    - Token expired: regenerate on control plane with 'kubeadm token create --print-join-command'"
    echo "    - Network: ensure port 6443 is reachable on the control plane"
    echo "    - Firewall: check iptables on both nodes"
    exit 1
}

# ---- Wait for kubelet to start -----------------------------------------------
log_info "Waiting for kubelet to become active..."
for i in $(seq 1 30); do
    if systemctl is-active --quiet kubelet; then
        log_info "kubelet is running."
        break
    fi
    sleep 2
done

# ---- Summary -----------------------------------------------------------------
echo ""
log_info "=== Worker node joined successfully ==="
log_info "Hostname: $(hostname)"
log_info "IP:       $(hostname -I | awk '{print $1}')"
echo ""
log_info "On the control plane, verify with:"
log_info "  kubectl get nodes -o wide"
log_info "  kubectl get pods -A -o wide"
echo ""
log_info "The node may take 30-60 seconds to become Ready (waiting for CNI)."
echo ""
log_info "Next: run 07-metallb.sh on the control plane"
