#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# generate_account_dirs.sh
#
# Queries AWS Organizations to discover accounts in the target OUs and
# generates the Terragrunt directory structure for SSO account assignments.
#
# Usage:
#   ./scripts/generate_account_dirs.sh [--dry-run]
#
# Prerequisites:
#   - AWS CLI v2 configured with credentials that can call
#     organizations:ListAccountsForParent
#   - jq installed
#
# For each active account in the target OUs, the script creates:
#
#   envs/<account_name>/account.hcl
#   envs/<account_name>/eu-west-1/region.hcl
#   envs/<account_name>/eu-west-1/sso-account-assignments/terragrunt.hcl
#
# The master account is SKIPPED -- it has its own dedicated layout
# (sso-configuration + sso-permission-sets).
# -----------------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENVS_DIR="${ROOT_DIR}/envs"

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
    echo "[DRY RUN] No files will be created."
    echo ""
fi

# ---------------------------------------------------------------------------
# Configuration — edit these to match your environment
# ---------------------------------------------------------------------------
TARGET_REGION="eu-west-1"
MASTER_PROFILE="master-admin"

# OU IDs to scan for workload accounts (add/remove as needed)
TARGET_OUS=(
    "ou-xxxx-cccccccc"  # Production OU
    "ou-xxxx-dddddddd"  # Development OU
    "ou-xxxx-bbbbbbbb"  # Services OU
)

# ---------------------------------------------------------------------------
# Validate prerequisites
# ---------------------------------------------------------------------------
if ! command -v aws &>/dev/null; then
    echo "Error: aws CLI not found. Install it first."
    exit 1
fi

if ! command -v jq &>/dev/null; then
    echo "Error: jq not found. Install it first."
    exit 1
fi

# Parse master account ID from envs/master/account.hcl
MASTER_ACCOUNT_HCL="${ENVS_DIR}/master/account.hcl"
if [[ ! -f "$MASTER_ACCOUNT_HCL" ]]; then
    echo "Error: ${MASTER_ACCOUNT_HCL} not found"
    exit 1
fi

MASTER_ACCOUNT_ID=$(grep 'aws_account_id' "$MASTER_ACCOUNT_HCL" \
    | grep -oE '[0-9]{12}' | head -1)

if [[ -z "${MASTER_ACCOUNT_ID:-}" ]]; then
    echo "Error: Could not parse aws_account_id from ${MASTER_ACCOUNT_HCL}"
    exit 1
fi

echo "Configuration:"
echo "  Target OUs:         ${TARGET_OUS[*]}"
echo "  Target Region:      ${TARGET_REGION}"
echo "  Master Account ID:  ${MASTER_ACCOUNT_ID} (skipped)"
echo "  Master Profile:     ${MASTER_PROFILE}"
echo ""

# ---------------------------------------------------------------------------
# Helper: sanitise AWS account name for use as a directory name
# ---------------------------------------------------------------------------
sanitize_name() {
    local name="$1"
    # Lowercase, replace spaces/underscores with hyphens, strip non-alphanum
    echo "$name" \
        | tr '[:upper:]' '[:lower:]' \
        | sed 's/[_ ]/-/g' \
        | sed 's/[^a-z0-9-]//g' \
        | sed 's/--*/-/g' \
        | sed 's/^-//;s/-$//'
}

# ---------------------------------------------------------------------------
# Create the sso-account-assignments terragrunt.hcl for a workload account
# ---------------------------------------------------------------------------
create_assignments_terragrunt() {
    local account_name="$1"
    local account_id="$2"
    local target_dir="$3"

    cat > "${target_dir}/terragrunt.hcl" <<TGEOF
###############################################################################
# ${account_name} — SSO Account Assignments
#
# Auto-generated by generate_account_dirs.sh
#
# Assigns SSO groups to this AWS account with specific permission sets.
# All SSO operations target the master account's IAM Identity Center.
###############################################################################

include "root" {
  path = find_in_parent_folders()
}

include "envcommon" {
  path   = "\${dirname(find_in_parent_folders())}/_envcommon/sso-account-assignments.hcl"
  expose = true
}

# ---------------------------------------------------------------------------
# Dependencies
# ---------------------------------------------------------------------------

dependency "sso_config" {
  config_path = "\${get_repo_root()}/envs/master/${TARGET_REGION}/sso-configuration"

  mock_outputs = {
    sso_instance_arn  = "arn:aws:sso:::instance/ssoins-0000000000000000"
    identity_store_id = "d-0000000000"
  }
}

dependency "permission_sets" {
  config_path = "\${get_repo_root()}/envs/master/${TARGET_REGION}/sso-permission-sets"

  mock_outputs = {
    permission_set_arns = {
      AdministratorAccess = "arn:aws:sso:::permissionSet/ssoins-0000000000000000/ps-0000000000000001"
      DeveloperAccess     = "arn:aws:sso:::permissionSet/ssoins-0000000000000000/ps-0000000000000002"
      ReadOnlyAccess      = "arn:aws:sso:::permissionSet/ssoins-0000000000000000/ps-0000000000000003"
    }
  }
}

# ---------------------------------------------------------------------------
# IMPORTANT: Override provider to use the MASTER account profile
#
# Account assignments must be made from the management account.
# ---------------------------------------------------------------------------

generate "provider_override" {
  path      = "provider_override.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    provider "aws" {
      region  = "${TARGET_REGION}"
      profile = "${MASTER_PROFILE}"

      default_tags {
        tags = {
          Project     = "google-sso"
          Environment = "${account_name}"
          ManagedBy   = "terraform"
        }
      }
    }
  EOF
}

# ---------------------------------------------------------------------------
# Inputs — customise the assignments for this account
# ---------------------------------------------------------------------------

locals {
  target_account_id = "${account_id}"
}

inputs = {
  account_assignments = [
    # Admins get full access
    {
      account_id          = local.target_account_id
      permission_set_name = "AdministratorAccess"
      principal_type      = "GROUP"
      principal_name      = "AWS-Admins"
    },
    # ReadOnly group gets read-only access
    {
      account_id          = local.target_account_id
      permission_set_name = "ReadOnlyAccess"
      principal_type      = "GROUP"
      principal_name      = "AWS-ReadOnly"
    },
    # Security audit
    {
      account_id          = local.target_account_id
      permission_set_name = "SecurityAudit"
      principal_type      = "GROUP"
      principal_name      = "AWS-SecurityAudit"
    },
  ]
}
TGEOF
}

# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------
ACCOUNT_COUNT=0
DIR_COUNT=0

for OU_ID in "${TARGET_OUS[@]}"; do
    echo "Querying accounts in OU: ${OU_ID}..."

    ACCOUNTS=$(aws organizations list-accounts-for-parent \
        --parent-id "$OU_ID" \
        --query "Accounts[?Status=='ACTIVE'].[Id,Name]" \
        --output text 2>/dev/null || true)

    if [[ -z "$ACCOUNTS" ]]; then
        echo "  Warning: No active accounts found in OU ${OU_ID} (or insufficient permissions)"
        continue
    fi

    while IFS=$'\t' read -r ACCOUNT_ID ACCOUNT_NAME; do
        # Skip the master account
        if [[ "$ACCOUNT_ID" == "$MASTER_ACCOUNT_ID" ]]; then
            echo "  Skipping ${ACCOUNT_NAME} (${ACCOUNT_ID}) -- master account"
            continue
        fi

        DIR_NAME=$(sanitize_name "$ACCOUNT_NAME")
        ACCOUNT_DIR="${ENVS_DIR}/${DIR_NAME}"
        REGION_DIR="${ACCOUNT_DIR}/${TARGET_REGION}"
        ASSIGNMENTS_DIR="${REGION_DIR}/sso-account-assignments"

        echo "  Account: ${ACCOUNT_NAME} (${ACCOUNT_ID}) -> ${DIR_NAME}/"

        # Create account.hcl if it doesn't exist
        if [[ ! -f "${ACCOUNT_DIR}/account.hcl" ]]; then
            if [[ "$DRY_RUN" == false ]]; then
                mkdir -p "$ACCOUNT_DIR"
                cat > "${ACCOUNT_DIR}/account.hcl" <<EOF
###############################################################################
# ${ACCOUNT_NAME} Account Configuration
#
# Auto-generated by generate_account_dirs.sh
###############################################################################

locals {
  account_name   = "${DIR_NAME}"
  aws_account_id = "${ACCOUNT_ID}"
  aws_profile    = "${DIR_NAME}-admin"
}
EOF
            fi
            echo "    Created: ${DIR_NAME}/account.hcl"
        else
            echo "    Exists:  ${DIR_NAME}/account.hcl"
        fi

        # Create region.hcl if it doesn't exist
        if [[ ! -f "${REGION_DIR}/region.hcl" ]]; then
            if [[ "$DRY_RUN" == false ]]; then
                mkdir -p "$REGION_DIR"
                cat > "${REGION_DIR}/region.hcl" <<EOF
locals {
  aws_region = "${TARGET_REGION}"
}
EOF
            fi
            echo "    Created: ${DIR_NAME}/${TARGET_REGION}/region.hcl"
        fi

        # Create sso-account-assignments if it doesn't exist
        if [[ -d "$ASSIGNMENTS_DIR" ]]; then
            echo "    Exists:  ${DIR_NAME}/${TARGET_REGION}/sso-account-assignments/"
        else
            if [[ "$DRY_RUN" == false ]]; then
                mkdir -p "$ASSIGNMENTS_DIR"
                create_assignments_terragrunt "$DIR_NAME" "$ACCOUNT_ID" "$ASSIGNMENTS_DIR"
            fi
            echo "    Created: ${DIR_NAME}/${TARGET_REGION}/sso-account-assignments/"
            DIR_COUNT=$((DIR_COUNT + 1))
        fi

        ACCOUNT_COUNT=$((ACCOUNT_COUNT + 1))
    done <<< "$ACCOUNTS"
done

echo ""
echo "Done. Processed ${ACCOUNT_COUNT} accounts, created ${DIR_COUNT} new assignment directories."
echo ""
if [[ "$DRY_RUN" == true ]]; then
    echo "This was a dry run. Re-run without --dry-run to create the directories."
else
    echo "Next steps:"
    echo "  1. Review and customise the generated account_assignments in each terragrunt.hcl"
    echo "  2. Deploy all assignments:"
    echo "     cd envs && terragrunt run-all plan"
    echo ""
    echo "  Or deploy a single account:"
    echo "     cd envs/<account-name>/${TARGET_REGION}/sso-account-assignments && terragrunt apply"
fi
