{{- if .Values.customIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.nominatim.fullname" . }}
  namespace: {{ include "chart.namespace" . | quote }}
  labels:
    app.kubernetes.io/name: nominatim
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    {{- if .Values.customIngress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- with .Values.customIngress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.customIngress.tls }}
  tls:
    - hosts:
        - {{ .Values.customIngress.hostname | quote }}
      secretName: {{ printf "%s-tls" .Values.customIngress.hostname }}
  {{- end }}
  rules:
    - host: {{ .Values.customIngress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "chart.nominatim.fullname" . }}
                port:
                  name: http
    {{- range .Values.customIngress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "chart.nominatim.fullname" $ }}
                port:
                  name: http
    {{- end }}
{{- end }}
