# -----------------------------------------------------------------------------
# envs/prodire/env.hcl
#
# Environment-level variables for the prodire (Production Ireland) environment.
#
# This is a multi-account environment. Each account in the target OUs gets its
# own leaf directory generated by scripts/generate_account_dirs.sh.
# The account_id below is a fallback; per-account values come from account.hcl.
# -----------------------------------------------------------------------------

locals {
  project     = "myproject"
  service     = "alb"
  environment = "prodire"
  account_id  = "000000000000"   # Override per-account in account.hcl

  # ---------------------------------------------------------------------------
  # Networking
  # ---------------------------------------------------------------------------
  vpc_id     = "vpc-0123456789abcdef0"   # Replace with actual VPC ID or use data source
  subnet_ids = []                         # Override per-account/region in leaf terragrunt.hcl
  internal   = false

  # ---------------------------------------------------------------------------
  # TLS
  # ---------------------------------------------------------------------------
  certificate_arn = "arn:aws:acm:eu-west-1:000000000000:certificate/00000000-0000-0000-0000-000000000000"

  # ---------------------------------------------------------------------------
  # Access Logs
  # ---------------------------------------------------------------------------
  enable_access_logs = true
  access_logs_bucket = ""   # Override per-account -- e.g. "${project}-${environment}-logs-${account_id}"
  access_logs_prefix = "alb"

  # ---------------------------------------------------------------------------
  # WAF
  # ---------------------------------------------------------------------------
  enable_waf      = true
  waf_rule_action = "count"   # "count" = monitor only, "none" = enforce/block

  # ---------------------------------------------------------------------------
  # Logging
  # ---------------------------------------------------------------------------
  log_retention_days = 180

  # ---------------------------------------------------------------------------
  # Multi-account targets
  #
  # Used by scripts/generate_account_dirs.sh to discover accounts from
  # AWS Organizations and scaffold per-account directories.
  # ---------------------------------------------------------------------------
  target_ou_ids = [
    "ou-xxxx-aaaaaaaa",   # Production Accounts OU
    "ou-xxxx-bbbbbbbb",   # Development Accounts OU
    "ou-xxxx-cccccccc",   # Services Accounts OU
  ]

  target_regions = [
    "eu-west-1",
    "af-south-1",
  ]
}
