[pg]
description = "Production PostgreSQL 18"
conninfo = host=127.0.0.1 user=barman dbname=proddb
streaming_conninfo = host=127.0.0.1 user=barman dbname=proddb
backup_method = postgres
streaming_archiver = on
slot_name = barman_slot
retention_policy = RECOVERY WINDOW OF 4 WEEKS
wal_retention_policy = main
archiver = off
create_slot = auto
