# ---------------------------------------------------------------
# values-systest.yaml — System Test (EU West) overrides
# ---------------------------------------------------------------

# -- Wrapper chart values (custom templates)
project: "geocoding"
account: "1111111111111"
region: "eu-west-1"
cidr_range: "10.134"

env:
  name: "systest"

networkpolicy:
  enabled: true

# -- Upstream nominatim subchart overrides
nominatim:
  ingress:
    enabled: false

  replicaCount: 1

  service:
    type: ClusterIP
    ports:
      http: 8080

  postgresql:
    enabled: false

  externalDatabase:
    existingSecretDsn: geocoding-systest-dbcreds-secrets
    host: geocoding-systest-psql-primary.geocoding-systest.svc
    user: nominatim_user

  initJob:
    enabled: false
    pbfUrl: https://download.geofabrik.de/africa/south-africa-latest.osm.pbf
    wikipediaUrl: https://nominatim.org/data/wikimedia-importance.sql.gz

  updates:
    enabled: true
    replicationUrl: https://download.geofabrik.de/africa/south-africa-updates/
    args:
      - |
        NOMINATIM_REPLICATION_MAX_DIFF=5000 nominatim replication --catch-up --threads 8

  nominatimUi:
    enabled: false

  serviceAccount:
    create: true

  flatnode:
    enabled: false

  autoscaling:
    enabled: false

  extraEnvVars:
    - name: NOMINATIM_REPLICATION_MAX_DIFF
      value: "5000"

  ingress:
    enabled: true
    hostname: geocode.atlas.systest.moya.app
    tls: false
    pathType: Prefix
    annotations:
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:597684347793:certificate/1906a572-9f32-40bb-ae90-804b7dd54307, arn:aws:acm:eu-west-1:597684347793:certificate/5c7c656b-8657-4cde-80ca-302cad2fecb9"
      alb.ingress.kubernetes.io/backend-protocol-version: HTTP1
      alb.ingress.kubernetes.io/group.name: "alb-external"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    extraHosts: []

  networkPolicy:
    enabled: true
    # Generic "access only from" rules
    ingressRules:
      accessOnlyFrom:
        enabled: true
      # Arbitrary custom ingress rules (list of raw NetworkPolicy ingress rules)
      customRules:
        - from:
            - ipBlock:
                cidr: "10.134.0.0/20"
            - ipBlock:
                cidr: "10.134.16.0/20"
            - ipBlock:
                cidr: "10.134.32.0/20"
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: "geocoding-systest"
          ports:
            - protocol: TCP
              port: 8080
