#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# generate_account_dirs.sh
#
# Queries AWS Organizations to discover accounts in the target OUs and
# generates the Terragrunt directory structure for each account/region
# combination.
#
# Usage:
#   ./scripts/generate_account_dirs.sh <environment>
#
# Example:
#   ./scripts/generate_account_dirs.sh prodire
#
# Prerequisites:
#   - AWS CLI v2 configured with credentials that can call organizations:ListAccountsForParent
#   - jq installed
# -----------------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <environment>"
    echo "Example: $0 prodire"
    exit 1
fi

ENVIRONMENT="$1"
ENV_DIR="${ROOT_DIR}/envs/${ENVIRONMENT}"

if [[ ! -f "${ENV_DIR}/env.hcl" ]]; then
    echo "Error: ${ENV_DIR}/env.hcl not found"
    exit 1
fi

TARGET_OUS=$(grep -A 20 'target_ou_ids' "${ENV_DIR}/env.hcl" \
    | grep -oP '"ou-[^"]+' \
    | sed 's/"//')

TARGET_REGIONS=$(grep -A 20 'target_regions' "${ENV_DIR}/env.hcl" \
    | grep -oP '"[a-z]+-[a-z]+-[0-9]+"' \
    | sed 's/"//g')

if [[ -z "$TARGET_OUS" ]]; then
    echo "No target_ou_ids found in ${ENV_DIR}/env.hcl"
    exit 1
fi

if [[ -z "$TARGET_REGIONS" ]]; then
    echo "No target_regions found in ${ENV_DIR}/env.hcl"
    exit 1
fi

echo "Environment: ${ENVIRONMENT}"
echo "Target OUs: $(echo "$TARGET_OUS" | tr '\n' ' ')"
echo "Target Regions: $(echo "$TARGET_REGIONS" | tr '\n' ' ')"
echo ""

ACCOUNT_COUNT=0

for OU_ID in $TARGET_OUS; do
    echo "Querying accounts in OU: ${OU_ID}..."

    ACCOUNTS=$(aws organizations list-accounts-for-parent \
        --parent-id "$OU_ID" \
        --query "Accounts[?Status=='ACTIVE'].[Id,Name]" \
        --output text 2>/dev/null || true)

    if [[ -z "$ACCOUNTS" ]]; then
        echo "  Warning: No active accounts found in OU ${OU_ID} (or insufficient permissions)"
        continue
    fi

    while IFS=$'\t' read -r ACCOUNT_ID ACCOUNT_NAME; do
        for REGION in $TARGET_REGIONS; do
            ACCOUNT_DIR="${ENV_DIR}/${REGION}/${ACCOUNT_ID}/psql"

            if [[ -d "$ACCOUNT_DIR" ]]; then
                echo "  Exists: ${ACCOUNT_DIR}"
                continue
            fi

            echo "  Creating: ${ACCOUNT_DIR} (${ACCOUNT_NAME})"
            mkdir -p "$ACCOUNT_DIR"

            cat > "${ENV_DIR}/${REGION}/${ACCOUNT_ID}/account.hcl" <<EOF
# Auto-generated by generate_account_dirs.sh
# Account: ${ACCOUNT_NAME}
# OU: ${OU_ID}

locals {
  account_id   = "${ACCOUNT_ID}"
  account_name = "${ACCOUNT_NAME}"
}
EOF

            cat > "${ACCOUNT_DIR}/terragrunt.hcl" <<'TGEOF'
# -----------------------------------------------------------------------------
# Auto-generated by generate_account_dirs.sh
# Deploys PSQL IAM Role into this account/region.
# -----------------------------------------------------------------------------

include "root" {
  path = find_in_parent_folders("terragrunt.hcl")
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("terragrunt.hcl"))}/_envcommon/psql.hcl"
  expose = true
}

locals {
  account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl"))
}

inputs = {
  # Override EKS OIDC provider per-account as needed:
  # eks_oidc_provider_arn = "arn:aws:iam::<account_id>:oidc-provider/..."
  # eks_oidc_provider_url = "https://oidc.eks.<region>.amazonaws.com/id/..."
}
TGEOF

            ACCOUNT_COUNT=$((ACCOUNT_COUNT + 1))
        done
    done <<< "$ACCOUNTS"
done

echo ""
echo "Done. Created ${ACCOUNT_COUNT} new account/region directories."
echo ""
echo "To deploy all accounts in an environment:"
echo "  cd envs/${ENVIRONMENT} && terragrunt run-all plan"
echo ""
echo "To deploy a single account/region:"
echo "  cd envs/${ENVIRONMENT}/<region>/<account_id>/psql && terragrunt plan"
